FROM php:7.1-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
	zlib1g-dev \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install zip \
	&& rm -rf /tmp/* /var/cache/apk/* /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php \
        && mv composer.phar /usr/local/bin/ \
        && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

ENV PATH="~/.composer/vendor/bin:./vendor/bin:${PATH}"
