#!/bin/sh

docker-compose exec php composer install
docker-compose exec php composer dump-autoload
docker-compose exec php php artisan mysql:createdb
docker-compose exec php php artisan migrate --seed
docker-compose exec php php artisan key:generate
